project_id = "bsgsrfuunponyqdykafv"

[functions.send-contact-email]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.marketplace-create-order]
verify_jwt = false

[functions.marketplace-download]
verify_jwt = false